import { ColorPalette } from '../types';

export const PRESET_PALETTES: ColorPalette[] = [
  {
    id: 'nysc-classic',
    name: 'NYSC Classic (Green & Gold)',
    primary: '#006837',
    accent: '#FBB03B',
    background: '#FFFDF9',
    cardBg: '#FFFFFF',
    textColor: '#1E293B',
    headingColor: '#006837',
    textOnPrimary: '#FFFFFF',
    textOnAccent: '#1F2937',
  },
  {
    id: 'navy-gold',
    name: 'Royal Navy & Gold',
    primary: '#0F294A',
    accent: '#E5A93C',
    background: '#F8FAFC',
    cardBg: '#FFFFFF',
    textColor: '#0F172A',
    headingColor: '#0F294A',
    textOnPrimary: '#FFFFFF',
    textOnAccent: '#0F172A',
  },
  {
    id: 'emerald-yellow',
    name: 'Vibrant Emerald',
    primary: '#047857',
    accent: '#FACC15',
    background: '#F0FDF4',
    cardBg: '#FFFFFF',
    textColor: '#064E3B',
    headingColor: '#047857',
    textOnPrimary: '#FFFFFF',
    textOnAccent: '#1F2937',
  },
  {
    id: 'maroon-champagne',
    name: 'Maroon & Champagne',
    primary: '#6B1D2F',
    accent: '#E6B87D',
    background: '#FDFBF7',
    cardBg: '#FFFFFF',
    textColor: '#291219',
    headingColor: '#6B1D2F',
    textOnPrimary: '#FFFFFF',
    textOnAccent: '#291219',
  },
  {
    id: 'black-gold',
    name: 'Onyx Prestige',
    primary: '#18181B',
    accent: '#F59E0B',
    background: '#F9FAFB',
    cardBg: '#FFFFFF',
    textColor: '#18181B',
    headingColor: '#18181B',
    textOnPrimary: '#FFFFFF',
    textOnAccent: '#18181B',
  },
];

export const DEFAULT_PALETTE = PRESET_PALETTES[0];
